config/routes.rb
Rails.application.routes.draw do
  resources :passengers
  resources :bookings
  resources :flights
  resources :airports
    root "flights#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, foreign_key: "departure_airport_id", class_name: "Airport"
  belongs_to :arrival_airport, foreign_key: "arrival_airport_id", class_name: "Airport"
  belongs_to :booked_flight, foreign_key: "booked_flight_id", class_name: "Booking"
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: %i[ show edit update destroy ]

  # GET /flights or /flights.json
  def index
    @flight = Flight.new
    query_search
    @airport_collection = Airport.all.map { |air| [ air.code, air.id ] }
    @flight_dates = Flight.all.map { |flight|  flight.flightstart.to_date }
  end


  # GET /flights/1 or /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights or /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: "Flight was successfully created." }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1 or /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: "Flight was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1 or /flights/1.json
  def destroy
    @flight.destroy!

    respond_to do |format|
      format.html { redirect_to flights_path, notice: "Flight was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def flight_params
      params.expect(flight: [ :departure, :arrival, :query[:departure, :arrival, :datestart] ])
    end
  def query_search
      flash.clear
    if params[:query].present?
      departure_airport = Airport.find_by(id: params[:query][:departure])
      arrival_airport = Airport.find_by(id: params[:query][:arrival])
      selected_date = Date.parse(params[:query][:datestart]) if params[:query][:datestart].present?
      @flights = Flight.where(departure_airport: departure_airport, arrival_airport: arrival_airport)
      @flights = Flight.where(departure_airport: departure_airport) if params[:query][:departure].present?
      @flights = Flight.where(arrival_airport: arrival_airport) if params[:query][:arrival].present?
      @flights = Flight.where(flightstart: selected_date) if params[:query][:datestart].present?
      @flights = Flight.where(departure_airport: departure_airport, arrival_airport: arrival_airport) if params[:query][:arrival].present? && params[:query][:departure].present?
      if params[:query][:departure] == "" && params[:query][:arrival] == ""
        if params[:query][:datestart].present?
          @flights = Flight.where(flightstart: selected_date.all_day)
        else
          @flights = []
        end

      end
      if @flights == []
      flash[:notice] = "Could not find an available flight. #{params[:query]}"
      @flights = Flight.all
      end
    else
      @flights = Flight.all
    end
   end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_flight.html.erb
<div id="<%= dom_id flight %>">
  <p>
    <strong>Departure:</strong>
    <%= flight.departure_airport.code %>
  </p>

  <p>
    <strong>Arrival:</strong>
    <%= flight.arrival_airport.code %>
  </p>

  <p>
    <strong>Flight Start:</strong>
    <%= flight.flightstart.strftime("%d/%m/%Y")%>
  </p>

</div>

app/views/flights/_form.html.erb
<%= simple_form_for :query, url: flights_path, method: :get do |f|%>

<%= f.input :departure, label: 'Departure Airport', collection: @airport_collection, required: false%>
<%= f.input :arrival, label: 'Arrival Airport', collection: @airport_collection, required: false %>
<%= f.input :datestart, label: 'Pick starting date:', collection:@flight_dates.uniq %>
<%= f.submit %>
<%end%>
<%= puts params%>

app/views/flights/edit.html.erb
<% content_for :title, "Editing flight" %>

<h1>Editing flight</h1>

<%= render "form", flight: @flight %>

<br>

<div>
  <%= link_to "Show this flight", @flight %> |
  <%= link_to "Back to flights", flights_path %>
</div>

app/views/flights/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Flights" %>

<h1>Flights</h1>
<%= render 'form' %>
<div id="flights">
    <%= simple_form_for :flight, url: new_booking_path, method: :get do |f|%>
      <%= f.collection_radio_buttons :id, @flights, :id, :flight_name%>
      <%= f.submit%>
    <%end%>
</div>

<%= link_to "New flight", new_flight_path %>

app/views/flights/new.html.erb
<% content_for :title, "New flight" %>

<h1>New flight</h1>

<%= render "form", flight: @flight %>

<br>

<div>
  <%= link_to "Back to flights", flights_path %>
</div>

app/views/flights/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @flight %>

<div>
  <%= link_to "Edit this flight", edit_flight_path(@flight) %> |
  <%= link_to "Back to flights", flights_path %>

  <%= button_to "Destroy this flight", @flight, method: :delete %>
</div>