config/routes.rb
Rails.application.routes.draw do
  resources :passengers
  resources :bookings
  resources :flights
  resources :airports
    root "flights#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :booked_flight, foreign_key: "booked_flight_id", class_name: "Flight"
  belongs_to :passenger_who_booked, foreign_key: "passenger_who_booked_id", class_name: "Passenger"
  accepts_nested_attributes_for :passenger_who_booked
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]

  # GET /bookings or /bookings.json
  def index
    flash[:notice] = params
    @bookings = Booking.all
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    flash[:notice] = params
    @booking = Booking.new
    @passenger = Passenger.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    flash[:notice] = params
    @booking = Booking.new(booked_flight_id: params[:booking][:booked_flight_id])
    puts "this is myparams: #{params}"
    @passenger = Passenger.new(name: params[:booking][:passenger][:name], email: params[:booking][:passenger][:email])
    p @passenger
    @booking.passenger_who_booked = @passenger
    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: "Booking was successfully created." }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: "Booking was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy!

    respond_to do |format|
      format.html { redirect_to bookings_path, notice: "Booking was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.expect(booking: [ :booked_flight_id, passenger: [ :name, :email ] ])
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">
  <p>
    <strong>Booked flight:</strong>
    <%= booking.booked_flight_id %>
  </p>
    <div>
      <%= booking.passenger_who_booked&.name %>
       
      <%= booking.passenger_who_booked&.email%>
    </div>
</div>

app/views/bookings/_form.html.erb
<%= flash[:notice] = params %>


<%= simple_form_for(@booking) do |f| %>

<% selected_flight_id = params[:flight][:id]  %>
<% selected_flight = Flight.find_by(id: selected_flight_id)%>

  <%= "You have selected: #{selected_flight.flight_name}"%>
  <h2>Flight Details:</h2>
    <%= "From: #{selected_flight.departure_airport.code}"%>
    <br>
    <%= "To: #{selected_flight.arrival_airport.code}"%>
    <br>
    <%= "Flight start: #{selected_flight.flightstart.strftime("%d/%m/%Y %H:%M")}"%>
    <br>
    <%= "Flight end: #{selected_flight.flightend.strftime("%d/%m/%Y %H:%M")}"%>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <%= f.simple_fields_for @passenger do |p|%>
      <%=p.input :name, label: 'Passenger Name: '%>
      <%=p.input :email, label: 'Passenger Email: '%>
    <%end%>
  <div class="form-inputs">
    <%= f.hidden_field :booked_flight_id, :value => selected_flight_id %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<% content_for :title, "Editing booking" %>

<h1>Editing booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Show this booking", @booking %> |
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Bookings" %>

<h1>Bookings</h1>

<div id="bookings">
  <% @bookings.each do |booking| %>
    <%= render booking %>
    <p>
      <%= link_to "Show this booking", booking %>
    </p>
  <% end %>
</div>

<%= link_to "New booking", new_booking_path %>

app/views/bookings/new.html.erb
<% content_for :title, "New booking" %>

<h1>New booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @booking %>

<div>
  <%= link_to "Edit this booking", edit_booking_path(@booking) %> |
  <%= link_to "Back to bookings", bookings_path %>

  <%= button_to "Destroy this booking", @booking, method: :delete %>
</div>