config/routes.rb
Rails.application.routes.draw do
  resources :passengers
  resources :bookings
  resources :flights
  resources :airports
    root "flights#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  has_many :bookings, foreign_key: "passenger_who_booked_id", class_name: "Booking"
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  before_action :set_passenger, only: %i[ show edit update destroy ]

  # GET /passengers or /passengers.json
  def index
    @passengers = Passenger.all
  end

  # GET /passengers/1 or /passengers/1.json
  def show
  end

  # GET /passengers/new
  def new
    @passenger = Passenger.new
  end

  # GET /passengers/1/edit
  def edit
  end

  # POST /passengers or /passengers.json
  def create
    @passenger = Passenger.new(passenger_params)

    respond_to do |format|
      if @passenger.save
        format.html { redirect_to @passenger, notice: "Passenger was successfully created." }
        format.json { render :show, status: :created, location: @passenger }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passengers/1 or /passengers/1.json
  def update
    respond_to do |format|
      if @passenger.update(passenger_params)
        format.html { redirect_to @passenger, notice: "Passenger was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @passenger }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passengers/1 or /passengers/1.json
  def destroy
    @passenger.destroy!

    respond_to do |format|
      format.html { redirect_to passengers_path, notice: "Passenger was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passenger
      @passenger = Passenger.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def passenger_params
      params.expect(passenger: [ :name, :email ])
    end
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/passengers/_form.html.erb
<%= simple_form_for(@passenger) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/passengers/_passenger.html.erb
<div id="<%= dom_id passenger %>">
  <p>
    <strong>Name:</strong>
    <%= passenger.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= passenger.email %>
  </p>

</div>

app/views/passengers/edit.html.erb
<% content_for :title, "Editing passenger" %>

<h1>Editing passenger</h1>

<%= render "form", passenger: @passenger %>

<br>

<div>
  <%= link_to "Show this passenger", @passenger %> |
  <%= link_to "Back to passengers", passengers_path %>
</div>

app/views/passengers/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Passengers" %>

<h1>Passengers</h1>

<div id="passengers">
  <% @passengers.each do |passenger| %>
    <%= render passenger %>
    <p>
      <%= link_to "Show this passenger", passenger %>
    </p>
  <% end %>
</div>

<%= link_to "New passenger", new_passenger_path %>

app/views/passengers/new.html.erb
<% content_for :title, "New passenger" %>

<h1>New passenger</h1>

<%= render "form", passenger: @passenger %>

<br>

<div>
  <%= link_to "Back to passengers", passengers_path %>
</div>

app/views/passengers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @passenger %>

<div>
  <%= link_to "Edit this passenger", edit_passenger_path(@passenger) %> |
  <%= link_to "Back to passengers", passengers_path %>

  <%= button_to "Destroy this passenger", @passenger, method: :delete %>
</div>