config/routes.rb
Rails.application.routes.draw do
  resources :passengers
  resources :bookings
  resources :flights
  resources :airports
    root "flights#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: "Flight", foreign_key: "departure_airport_id"
  has_many :arriving_flights, class_name: "Flight", foreign_key: "arrival_airport_id"
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  before_action :set_airport, only: %i[ show edit update destroy ]

  # GET /airports or /airports.json
  def index
    @airports = Airport.all
  end

  # GET /airports/1 or /airports/1.json
  def show
  end

  # GET /airports/new
  def new
    @airport = Airport.new
  end

  # GET /airports/1/edit
  def edit
  end

  # POST /airports or /airports.json
  def create
    @airport = Airport.new(airport_params)

    respond_to do |format|
      if @airport.save
        format.html { redirect_to @airport, notice: "Airport was successfully created." }
        format.json { render :show, status: :created, location: @airport }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airports/1 or /airports/1.json
  def update
    respond_to do |format|
      if @airport.update(airport_params)
        format.html { redirect_to @airport, notice: "Airport was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @airport }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airports/1 or /airports/1.json
  def destroy
    @airport.destroy!

    respond_to do |format|
      format.html { redirect_to airports_path, notice: "Airport was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airport
      @airport = Airport.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def airport_params
      params.expect(airport: [ :code ])
    end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/views/airports/_airport.html.erb
<div id="<%= dom_id airport %>">
  <p>
    <strong>Code:</strong>
    <%= airport.code %>
  </p>

</div>

app/views/airports/_form.html.erb
<%= form_with(model: airport) do |form| %>
  <% if airport.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(airport.errors.count, "error") %> prohibited this airport from being saved:</h2>

      <ul>
        <% airport.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :code, style: "display: block" %>
    <%= form.text_field :code %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/airports/edit.html.erb
<% content_for :title, "Editing airport" %>

<h1>Editing airport</h1>

<%= render "form", airport: @airport %>

<br>

<div>
  <%= link_to "Show this airport", @airport %> |
  <%= link_to "Back to airports", airports_path %>
</div>

app/views/airports/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Airports" %>

<h1>Airports</h1>

<div id="airports">
  <% @airports.each do |airport| %>
    <%= render airport %>
    <p>
      <%= link_to "Show this airport", airport %>
    </p>
  <% end %>
</div>

<%= link_to "New airport", new_airport_path %>

app/views/airports/new.html.erb
<% content_for :title, "New airport" %>

<h1>New airport</h1>

<%= render "form", airport: @airport %>

<br>

<div>
  <%= link_to "Back to airports", airports_path %>
</div>

app/views/airports/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @airport %>

<div>
  <%= link_to "Edit this airport", edit_airport_path(@airport) %> |
  <%= link_to "Back to airports", airports_path %>

  <%= button_to "Destroy this airport", @airport, method: :delete %>
</div>